theme: minima 
title: Pickles: Our new messiah? 
author: Peg Leahay
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We just really like pickles and feel like they don't get the 
  attention they should. And, yeah we should question life and 
  those answers we typically get for things like religion and who 
  Jesus/God is so why can't it be pickles? Like not Tommy Pickles
  like just actual brined cucumbers. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
